export { default as ArrowRightIcon } from './ArrowRightIcon';
export { default as CalendarIcon } from './CalendarIcon';
export { default as MarkerIcon } from './MarkerIcon';
export { default as CheckboxIcon } from './CheckboxIcon';
export { default as FileIcon } from './FileIcon';
export { default as TrashIcon } from './TrashIcon';
export { default as ReferenceIcon} from './ReferenceIcon';
export { default as SurveyIcon } from './SurveyIcon';
export { default as WhiteHomeIcon } from './WhiteHomeIcon';
export { default as ClassRegistIcon } from './ClassRegistIcon';
export { default as NoticeIcon } from './NoticeIcon';